### PR TITLE
mel/redux-store-slice

### PR DESCRIPTION
**Pull request by MelodyDuan**
added two files: store.js contains redux store logic, productsSlice.js contains redux slice for state management.

### CODE REVIEW

**Review by ctolmsted — CHANGES_REQUESTED** [review]
Please not to main

**Review by ctolmsted — APPROVED** [review]
Looks great! Nice sudo-code!

**Comment by jesswang-dev** [comment]
Wow, melody! I love your pseudocode! so detailed!

**Comment by tk-0311** [comment]
Great job everyone!

**Pull request merged**
