### PR TITLE
Jess/server-boilerplate

### PR DESCRIPTION
**Pull request by jesswang-dev**
Server boilerplate. Please approve!

### CODE REVIEW

**Comment by MelodyDuan** [comment]
Please to main

**Review by ctolmsted — COMMENTED** [review]
Great job!

**Comment by MelodyDuan** [comment]
please rename pull request to something more descriptive, thanks.

**Review by MelodyDuan — APPROVED** [review]
server boiler plate looks good. no conflicts. great job!

**Pull request merged**
